## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np

In [22]:
a = np.arange(0,9).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.dot(a,b)
print(c)




[[ 45  48  51]
 [162 174 186]
 [279 300 321]]


In [29]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Write a NumPy program to compute the determinant of a given square array

In [64]:
x = np.arange(10,14).reshape(2,2)
dete = np.linalg.det(x)
print(dete)

-2.000000000000014


## Write a NumPy program to compute the cross product of two given vectors

In [63]:
s = np.arange(1,4)
w = np.arange(5,8)
result = np.cross(s,w)
print(result)

[-4  8 -4]


## Write a NumPy program to compute the condition number of a given matrix
the condition number of a function measures how much the output value of the function can change for a small change in the input argument. This is used to measure how sensitive a function is to changes or errors in the input, and how much error in the output results from an error in the input.

*hint: look for something similar in the `linalg` module*1

In [56]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
print(np.linalg.cond(a))

2.4115596651225356e+16


## Write a NumPy program to compute the inverse of a given matrix

In [55]:
u = np.arange(0,4).reshape(2,2)
print (u)
print(np.linalg.inv(u))

[[0 1]
 [2 3]]
[[-1.5  0.5]
 [ 1.   0. ]]
